server:
  port: 8080
  tomcat:
    max-http-header-size: 3145728  
spring:
  application:
    name: shabao-example
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.91.220.42:3306/shabao_example?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: master
    password: 19911105man
  redis:
    database: 0
    port: 6379
    host: 47.91.220.42
    password: 19911105man
    pool:
      max-active: 20
  
#mybatis
#mybatis:
  #实体类包名，设置后可以用类名代替全路径名称
#  type-aliases-package: com.xiaoshabao.example.entity
  #设置mapper存放位置
#  mapper-locations: classpath:mapper/**.xml
  #开启驼峰命名规范
#  configuration:
#    mapUnderscoreToCamelCase: true
    
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xiaoshabao.bill.example.entity
#  typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 2
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      # Sequence序列接口实现类配置
      #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level:
    root: DEBUG
    com.xiaoshabao.example.mapper: DEBUG
#  path: C:/logs/log.log